---
language: python
python: '2.7'
sudo: false
install:
- python bootstrap.py -c buildout-linux-x86.cfg
- bin/buildout -N -t 30 -c buildout-linux-x86.cfg
before_script:
- source bin/activate
- make
- node phantomrobot.js 1>/dev/null &
script: pybot tests
